"""add notifications_enabled to users

Revision ID: 59f8771fe974
Revises: 3394a6849619
Create Date: 2026-09-19 21:40:22.292795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59f8771fe974'
down_revision: Union[str, Sequence[str], None] = '3394a6849619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    server_default backfills existing rows with True in the same ALTER
    TABLE statement — Postgres applies it to every existing row before
    the NOT NULL constraint is enforced, so this is safe even with data
    already in the table (unlike a plain nullable=False with no default).
    """
    op.add_column(
        'users',
        sa.Column('notifications_enabled', sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # Drop the server default after backfilling — new rows should get
    # their default from the application (models.py), not the database,
    # keeping one source of truth for defaults.
    op.alter_column('users', 'notifications_enabled', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'notifications_enabled')
    # ### end Alembic commands ###
